name: Gatsby Publish

on:
  push:
    branches:
      - master
env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}
jobs:
  spectral:
    name: spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: curl -L "https://spectral-us.dome9.com/latest/x/sh?dsn=$SPECTRAL_DSN" | sh
      - name: Scan
        run: $HOME/.spectral/spectral scan
  build:
    needs: spectral
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish Gatsby site
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
